---
# tasks file for win_domain_user
 - name: Ensure user bob is present with address information
   win_domain_user:
     name: "{{ item.name }}"
     firstname: "{{ item.firstname }}"
     surname: "{{ item.lastname }}"
     password: "{{ item.password }}"
     state: present
   with_items:
      - "{{ user_info }}"
