---
# tasks file for win_ad_install
 - name: Install AD-Domain-Services feature
   win_feature: 
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present
 
 - name: win domain module
   win_domain:
    dns_domain_name: ad1.fb4d.example.opentlc.com
    safe_mode_password: "{{ansible_password}}"
   register: out
 - name: display
   debug: 
     var: out
 - name: reboot if needed
   win_reboot:
   when: out.reboot_required

